# Port of HTTP(S) proxy server on the local end
port: 3333
# Port of SOCKS5 proxy server on the local end
socks-port: 23456
# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
redir-port: 23457
# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true
# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule
# RESTful web API listening address
external-controller: 127.0.0.1:9990
secret: "xtaozi-clash"
log-level: error
experimental:
  ignore-resolve-fail: true
profile:
  store-selected: true
ipv6: false
tproxy: true
tproxy-port: 23458
# Static hosts for DNS server and connection establishment (like /etc/hosts)
hosts:
  services.googleapis.cn: 74.125.193.94
dns:
  enable: true
  listen: :23453
  ipv6: false
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  fake-ip-filter:
    - '*.lan'
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://101.101.101.101:853 # DNS over TLS
    - https://doh.pub/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp
  fallback:
    - 127.0.0.1:23333
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - 101.6.6.6:5353
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - "+.netflix.com.edgesuite.net"
      - "+.fast.com"
      - "+.netflix.com"
      - "+.netflix.net"
      - "+.netflixdnstest0.com"
      - "+.netflixdnstest1.com"
      - "+.netflixdnstest2.com"
      - "+.netflixdnstest3.com"
      - "+.netflixdnstest4.com"
      - "+.netflixdnstest5.com"
      - "+.netflixdnstest6.com"
      - "+.netflixdnstest7.com"
      - "+.netflixdnstest8.com"
      - "+.netflixdnstest9.com"
      - "+.nflxext.com"
      - "+.nflximg.com"
      - "+.nflximg.net"
      - "+.nflxso.net"
      - "+.nflxvideo.net"
proxies:
proxy-groups:
rule-providers:
rules:
